Some tests
Plus a few small bugfixes and tweaks as a result of
writing the tests. Hooray?

diff --git a/araddclient b/araddclient
--- a/araddclient
+++ b/araddclient
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-help()
+print_help()
 {
   echo "" >&2
   echo "araddclient -- dynamic DNS client for v4/v6 updates to Cloudflare" >&2
@@ -43,6 +43,7 @@ help()
 load_conf()
 {
   local conf="$1"
+  clear_conf
   if [[ -z "$conf" ]]; then
     conf="$(dirname $0)/config.conf"
   fi
@@ -62,6 +63,13 @@ load_conf()
   return $?
 }
 
+clear_conf()
+{
+  for var in server login password zone hosts use_v6 use_v4 v4_method v6_method v6_if; do
+    unset $var
+  done
+}
+
 verify_conf()
 {
   for var in server login password zone hosts; do
@@ -72,8 +80,8 @@ verify_conf()
     fi
   done
   if [[ $use_v6 == "yes" ]]; then
-    if [[ -z "$v6_if" ]]; then
-      echo "use_v6 requires v6_if to be defined" >&2
+    if [[ -z "$v6_if" && "$v6_method" == "ifaddr" ]]; then
+      echo "use_v6 with v6_method=$v6_method requires v6_if to be defined" >&2
       return 1
     fi
   fi
@@ -105,10 +113,12 @@ icanhazip()
   local protocol_ver="$1"
   result=$(curl -s -$protocol_ver 'https://icanhazip.com/')
   if [[ $verbose && $protocol_ver == 6 ]]; then
-    if_result=$(ifaddr)
-    if [[ $if_result != $result ]]; then
-      echo "  Warning: icanhazip and ifaddr disagree: $result != $if_result" >&2
-      echo "  Warning: You are probably sending your temporary/private IPv6 address. Consider using v6_method=ifaddr." >&2
+    if [[ ! -z $v6_if ]]; then
+      if_result=$(ifaddr)
+      if [[ $if_result != $result ]]; then
+        echo "  Warning: icanhazip and ifaddr disagree: $result != $if_result" >&2
+        echo "  Warning: You are probably sending your temporary/private IPv6 address. Consider using v6_method=ifaddr." >&2
+      fi
     fi
   fi
   echo $result
@@ -139,6 +149,7 @@ get_ipv4()
   local result=$($v4_method 4)
   if [ $verbose ]; then echo "  Found $result" >&2; echo "" >&2; fi
   echo $result
+  [[ -z $result ]] && return 1 || return 0
 }
 
 get_ipv6()
@@ -147,6 +158,7 @@ get_ipv6()
   local result=$($v6_method 6)
   if [ $verbose ]; then echo "  Found $result" >&2; echo "" >&2; fi
   echo $result
+  [[ -z $result ]] && return 1 || return 0
 }
 
 call_api()
@@ -181,6 +193,26 @@ call_api()
   "${cmd[@]}"
 }
 
+set_ipv6_for_hosts()
+{
+  local hosts="$1"
+  local ipv6="$2"
+  if [ $verbose ]; then echo "Setting IPv6" >&2; fi
+  for host in $hosts; do
+    set_ipv6_addr $zone_id $host $ipv6
+  done
+  if [ $verbose ]; then echo "" >&2; fi
+}
+
+set_ipv4_for_hosts()
+{
+  if [ $verbose ]; then echo "Setting IPv4" >&2; fi
+  for host in $hosts; do
+    set_ipv4_addr $zone_id $host $ipv4
+  done
+  if [ $verbose ]; then echo "" >&2; fi
+}
+
 get_zone()
 {
   local zone_name="$1"
@@ -189,6 +221,12 @@ get_zone()
   result=$(call_api "$url" | jq -r '.result[0].id')
   if [ $verbose ]; then echo "  Found $result" >&2; echo "" >&2; fi
   echo $result
+  if [[ -z $result ]]; then
+    echo "Unable get get Cloudlfare zone ID" >&2
+    return 1
+  else
+    return 0
+  fi
 }
 
 get_record()
@@ -289,15 +327,13 @@ set_ipv4_addr()
   update_record "$zone_id" "$host_name" "$addr" A
 }
 
-(which jq >/dev/null) || (echo "Please install 'jq'"; exit)
-
 parse_args()
 {
   while (( "$#" )); do
     case $1 in
       -h|--help)
-        help
-        exit
+        print_help
+        return 1
         ;;
       -v)
         verbose=$(($verbose + 1))
@@ -315,53 +351,45 @@ parse_args()
         ;;
     esac
   done
+  return 0
 }
 
-parse_args "$@"
-
-load_conf "$conf" || (help ; exit)
-
-if [[ $use_v4 == "yes" ]]; then
-  ipv4=$(get_ipv4)
-  if [[ -z "$ipv4" ]]; then
-    echo "Failed to get an IPv4 address" >&2
-    use_ipv4="no"
+require_prereqs()
+{
+  which jq >/dev/null
+  if [[ $? -ne 0 ]]; then
+    echo "Please install 'jq'"
+    return 1
   fi
-fi
+}
 
-if [[ $use_v6 == "yes" ]]; then
-  ipv6=$(get_ipv6)
-  if [[ -z "$ipv6" ]]; then
-    echo "Failed to get an IPv6 address" >&2
-    use_ipv6="no"
+get_and_assert_ips()
+{
+  [[ $use_v4 == "yes" ]] && ipv4=$(get_ipv4) || echo "Failed to get an IPv4 address" >&2
+  [[ $use_v6 == "yes" ]] && ipv6=$(get_ipv6) || echo "Failed to get an IPv6 address" >&2
+  if [[ -z "$ipv4" && -z "$ipv6" ]]; then
+    echo "Failed to get any IP address to update" >&2
+    return 1
+  else
+    return 0
   fi
-fi
+}
 
-if [[ $use_v4 != "yes" && $use_v6 != "yes" ]]; then
-  echo "Couldn't get an IPv4 or IPv6 address. Aborting!" >&2
-  exit
-fi
+initialize()
+{
+  require_prereqs || return 1
+  parse_args "$@" || return 2
+  load_conf "$conf" || (print_help ; return 3)
+}
 
-zone_id=$(get_zone "$zone")
-if [[ -z $zone_id ]]; then
-  echo "Couldn't find zone '$zone'"
-  exit
-fi
-
-# Update IPv6
-if [[ $use_v6 == "yes" ]]; then
-  if [ $verbose ]; then echo "Setting IPv6" >&2; fi
-  for host in $hosts; do
-    set_ipv6_addr $zone_id $host $ipv6
-  done
-  if [ $verbose ]; then echo "" >&2; fi
-fi
-
-# Update IPv4
-if [[ $use_v4 == "yes" ]]; then
-  if [ $verbose ]; then echo "Setting IPv4" >&2; fi
-  for host in $hosts; do
-    set_ipv4_addr $zone_id $host $ipv4
-  done
-  if [ $verbose ]; then echo "" >&2; fi
+if [[ $(basename "$0") == "araddclient" ]]; then
+  initialize "$@" || exit
+  get_and_assert_ips || exit
+  zone_id=$(get_zone "$zone") || exit
+  if [[ $use_v6 == "yes" ]]; then
+    set_ipv6_for_hosts "$hosts" "$ipv6"
+  fi
+  if [[ $use_v4 == "yes" ]]; then
+    set_ipv6_for_hosts "$hosts" "$ipv6"
+  fi
 fi
